version: '2'

services:

  postgres:
    image: 'postgres:9.6.3'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  web:
    depends_on:
      - 'postgres'
    build: .
    ports:
      - '9292:9292'
    volumes:
      - '.:/kpktbot'

volumes:
  postgres:

